version: '3' # 도커 컴포저의 버전
services: # 이곳에서 실행하려는 컨테이너들을 정의
  redis-server: # 컨테이너 이름 1
    image: 'redis' # 컨테이너에서 사용하는 이미지
  node-app: # 컨테이너 이름 2
    build: . # 현 디렉토리에 있는 Dockerfile 사용
    ports: # 포트 맵핑 로컬 포트 : 컨테이너 포트
      - '5000:8080'